version: "3"
services:
  nginx:
    image: nginx:1.23-alpine
    ports:
      - "9005:80"
    volumes:
      - "./src/nginx/site.conf:/etc/nginx/conf.d/default.conf"
    depends_on:
      - web-public
  web-public:
    build: .
    volumes:
      - "./src/web-public:/var/www/html"
